initial_dump_directory: /media/obkms/XML2/
turtle_directory: /media/obkms/RDF/
bdj_endpoint: http://bdj.pensoft.net/lib/journal_archive.php?journal=bdj
zookeys_endpoint: http://zookeys.pensoft.net/lib/journal_archive.php?journal=zookeys
